# Generated by Django 2.0.1 on 2018-02-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180119_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
